WIP: workflow tests

diff --git a/.github/workflows/maven-central-release.yaml b/.github/workflows/maven-central-release.yaml
--- a/.github/workflows/maven-central-release.yaml
+++ b/.github/workflows/maven-central-release.yaml
@@ -2,15 +2,37 @@ name: Publish "Telegram InitData" package to the Maven Central Repository
 
 on:
   push:
-    branches:
-      - main
+    branches: [main]
 
 permissions:
   contents: write
 
 jobs:
+  check-version:
+    runs-on: ubuntu-latest
+    outputs:
+      PKG_VERSION: ${{ steps.package-version.outputs.PKG_VERSION }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install xmlstarlet
+        run: sudo apt-get update && sudo apt-get install xmlstarlet
+      - name: Fetch project version and set PKG_VERSION
+        id: package-version
+        run: |
+          echo "PKG_VERSION=$(xmlstarlet sel -t -v '/project/version' pom.xml)" >> "$GITHUB_OUTPUT"
+          echo $(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" -t -v "/x:project/x:version" pom.xml)
+          git ls-remote --tags origin
+      - name: Check release version already exists
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          if git ls-remote --tags origin | grep -q "refs/tags/${PKG_VERSION}"; then
+            echo "Release ${PKG_VERSION} already exist, aborting!"
+            exit 1
+          fi
   build:
     runs-on: ubuntu-latest
+    needs: [ check-version ]
     steps:
       - uses: actions/checkout@v4
       - name: JDK setup
@@ -18,9 +40,6 @@ jobs:
         with:
           java-version: '11'
           distribution: 'temurin'
-      - name: Get package version
-        id: package-version
-        run: echo "PKG_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
       - name: Build package
         run: mvn -B package --file pom.xml
       - uses: actions/upload-artifact@v4
@@ -30,35 +49,32 @@ jobs:
             ${{ github.workspace }}/target
   release:
     runs-on: ubuntu-latest
-    needs: [ build ]
+    needs: [ check-version, build ]
+    env:
+      PKG_VERSION: ${{ needs.build.outputs.PKG_VERSION }}
     steps:
       - uses: actions/checkout@v4
-      - name: Check version release exists
-        env:
-          PKG_VERSION: ${{ needs.build.package-version.outputs.PKG_VERSION }}
-        run: echo $PKG_VERSION
-#        run: |
-#          git config --local user.email "action@github.com"
-#          git config --local user.name "GitHub Action"
-#          if ! git ls-remote --tags origin | grep -q "refs/tags/${PKG_VERSION}"; then
-#            git tag -a "${PKG_VERSION}" -m "Release ${PKG_VERSION}"
-#            git push origin "${PKG_VERSION}"
-#          else
-#            echo "Release ${PKG_VERSION} already exist aborting"
-#            exit 1
-#      - uses: ncipollo/release-action@v1
-#        with:
-#          artifacts: "release.tar.gz,foo/*.txt"
-#          tag: $PKG_VERSION
-
-      - name: Create Release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Check release version already exists
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          if ! git ls-remote --tags origin | grep -q "refs/tags/${PKG_VERSION}"; then
+            git tag -a "${PKG_VERSION}" -m "Release ${PKG_VERSION}"
+            git push origin "${PKG_VERSION}"
+          else
+            echo "Release ${PKG_VERSION} already exist aborting"
+            exit 1
+      - uses: actions/download-artifact@v4
         with:
-          tag_name: 'v${{ github.run_number }}'
-          release_name: 'Release v${{ github.run_number }}'
-          body: 'Description of the changes in this release'
+          name: target
+          path: ${{ github.workspace }}/target
+      - name: Create Release
+        uses: ncipollo/release-action@v1
+        with:
+          tag: ${{ env.PKG_VERSION }}
+          name: "v${{ env.PKG_VERSION }}"
+          body: ${{ github.event.head_commit.message }}
+          artifacts: "target/${{ github.event.repository.name }}*.jar"
   publish-maven-central:
     runs-on: ubuntu-latest
     needs: [ release ]
